config/routes.rb
Comidero::Application.routes.draw do
  get "home/index"

  match 'ofertas/:wday' => 'home#index', :constraints => {:wday => /lunes|martes|miercoles|jueves|viernes|sabado|domingo/}

  resources :ofertas do
    collection do
    get '/:restaurant/:titulo-:id' => 'ofertas#show'
      end
  end
  resources :restaurants

  root :to => "home#index"

end

app/models/address.rb
# -*- coding: undecided -*-
class Address < ActiveRecord::Base
  belongs_to :oferta
  geocoded_by :full_street_address   # can also be an IP address
  after_validation :geocode        

  def full_street_address
    "México, Jalisco, Guadalajara, " + self.street
  end

end

app/models/main_oferta.rb
class MainOferta < ActiveRecord::Base
  belongs_to :oferta
end

app/models/oferta.rb
# -*- coding: utf-8 -*-
class Oferta < ActiveRecord::Base
belongs_to :restaurant
has_many :main_ofertas

has_attached_file :picture, 
  :styles => { :medium => "400x350#", :thumb => "170x170#" },
  :storage => :s3,
  :s3_credentials => "#{Rails.root.to_s}/config/s3.yml",
  :path => "/:style/:id/:filename"

validates_attachment_presence :picture
validates_attachment_content_type :picture, :content_type => ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] 
#  :content_type => { :content_type => ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] }

  scope :by_wday, lambda {|wday| where("ofertas.days like '%?%'", wday).order("created_at DESC") unless wday.nil?}

  def valid_days
    wdays = ['lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado', 'domingo']
    oferta_wdays = []
    (1..7).each do |i|
      if self.days =~ /#{i}/
        oferta_wdays << wdays[i]
      end
    end

    return oferta_wdays
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
has_many :addresses, :dependent => :destroy
accepts_nested_attributes_for :addresses
has_many :ofertas, :dependent => :destroy
accepts_nested_attributes_for :ofertas

has_attached_file :logo,
  :styles => { :medium => "300x300>", :thumb => "200x200>" },
  :storage => :s3,
  :s3_credentials => "#{Rails.root.to_s}/config/s3.yml",
  :path => "/:style/:id/:filename"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

    wday = 0
    case params[:wday]
      when 'lunes'; wday = 1;
      when 'martes'; wday = 2;
      when 'miercoles'; wday = 3;
      when 'jueves'; wday = 4;
      when 'viernes'; wday = 5;
      when 'sabado'; wday = 6;
      when 'domingo'; wday = 7;
      else
      wday = Time.now.wday
    end

    @ofertas = Oferta.by_wday(wday)

    @oferta = MainOferta.find(wday).oferta rescue @oferta = @ofertas.last
  end

end

app/controllers/ofertas_controller.rb
class OfertasController < ApplicationController
  # GET /ofertas
  # GET /ofertas.xml
  def index
    @ofertas = Oferta.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @ofertas }
    end
  end

  # GET /ofertas/1
  # GET /ofertas/1.xml
  def show
    @oferta = Oferta.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @oferta }
    end
  end

  # GET /ofertas/new
  # GET /ofertas/new.xml
  def new
    @oferta = Oferta.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @oferta }
    end
  end

  # GET /ofertas/1/edit
  def edit
    @oferta = Oferta.find(params[:id])
  end

  # POST /ofertas
  # POST /ofertas.xml
  def create
    @oferta = Oferta.new(params[:oferta])
    @oferta.days.delete_if{|x| x == "0"}
    respond_to do |format|
      if @oferta.save
        format.html { redirect_to(@oferta, :notice => 'Oferta was successfully created.') }
        format.xml  { render :xml => @oferta, :status => :created, :location => @oferta }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @oferta.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ofertas/1
  # PUT /ofertas/1.xml
  def update
    @oferta = Oferta.find(params[:id])

    respond_to do |format|
      if @oferta.update_attributes(params[:oferta])
        format.html { redirect_to(@oferta, :notice => 'Oferta was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @oferta.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ofertas/1
  # DELETE /ofertas/1.xml
  def destroy
    @oferta = Oferta.find(params[:id])
    @oferta.destroy

    respond_to do |format|
      format.html { redirect_to(ofertas_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @restaurants }
    end
  end

  # GET /restaurants/1
  # GET /restaurants/1.xml
  def show
    @restaurant = Restaurant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @restaurant }
    end
  end

  # GET /restaurants/new
  # GET /restaurants/new.xml
  def new
    @restaurant = Restaurant.new
    @restaurant.addresses.build
    @restaurant.ofertas.build
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @restaurant }
    end
  end

  # GET /restaurants/1/edit
  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  # POST /restaurants
  # POST /restaurants.xml
  def create
    @restaurant = Restaurant.new(params[:restaurant])
    @restaurant.ofertas.first.days.delete_if{|x| x == "0"}
    
    respond_to do |format|
      if @restaurant.save
        #format.html { redirect_to(@restaurant, :notice => 'Restaurant was successfully created.') }
        format.html { redirect_to(root_url) }
        format.xml  { render :xml => @restaurant, :status => :created, :location => @restaurant }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @restaurant.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /restaurants/1
  # PUT /restaurants/1.xml
  def update
    @restaurant = Restaurant.find(params[:id])

    respond_to do |format|
      if @restaurant.update_attributes(params[:restaurant])
        format.html { redirect_to(@restaurant, :notice => 'Restaurant was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @restaurant.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.xml
  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    respond_to do |format|
      format.html { redirect_to(restaurants_url) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/application_helper.rb
# -*- coding: utf-8 -*-
module ApplicationHelper
  
  def day_list
    today = Time.now.wday - 1
    days = ['lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado', 'domingo']
    sorted_days = []
    (0..6).each do |i|
      sorted_days << days[today + i]
      today = (i * -1) -1 if today + i == 6
    end

    return sorted_days
  end

  def fecha_hoy
    today = Time.now.wday - 1
    days = ['lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado', 'domingo']
    if params[:wday]
      dia = params[:wday]
      dia = "miércoles" if params[:wday] == "miercoles"
      dia = "sábado" if params[:wday] == "sabado"
      return dia
    else
      return days[today] + " " + Time.now.day.to_s + " de junio"
    end
  end

  def cool_oferta_url(oferta)
    ofertas_url + "/" + oferta.restaurant.name.parameterize + "/" + oferta.description.parameterize + "-" + oferta.id.to_s
  end
  
end

app/helpers/ofertas_helper.rb
# -*- coding: utf-8 -*-
module OfertasHelper

  def oferta_full_description(oferta, hoy=nil)
    wdays = ['lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado', 'domingo']

    if hoy and oferta.days =~ /#{Time.now.wday}/
      "Hoy " + wdays[Time.now.wday-1] + ". " + oferta.description + " en " + oferta.restaurant.name.titleize + "."
    else
      oferta.description + " en " + oferta.restaurant.name.titleize + "."
    end
  end
  
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/home/index.html.haml
%h1 Ofertas del día, #{fecha_hoy}.

-if @oferta
  #main_oferta
    .social_main
      .fb-like{"data-href"=>cool_oferta_url(@oferta), "data-send" => "false", "data-width" => "80", "data-layout" => "button_count", "data-show-faces" => "false"}
      %a.twitter-share-button{:href => "https://twitter.com/share", "data-url" => cool_oferta_url(@oferta), "data-lang" => "en", "data-text" => oferta_full_description(@oferta, true), "data-via" => "comidero"} tweet

    .imagen
      .imagen2
        =image_tag(@oferta.picture.url(:medium))
    .info
      %h2
        =@oferta.description.titleize
        %br
      %span=' en ' + @oferta.restaurant.name.titleize
      %br
      %br
      -if !@oferta.hour.blank?
        %strong Horario en el que aplica
        %br
        =@oferta.hour
        %br
      %br
      -if @oferta.restaurant.addresses
        -if !@oferta.restaurant.addresses.first.street.blank?
          %strong Dirección
          %br
          =@oferta.restaurant.addresses.first.street
          %br
        %br
        -if !@oferta.restaurant.addresses.first.phone.blank?
          %strong Teléfono
          %br
          =@oferta.restaurant.addresses.first.phone
          %br
          %br
      -if !@oferta.conditions.blank?
        .conditions
          %strong Condiciones
          %br
          =@oferta.conditions
          %br
          %br
    =link_to("Ver más", cool_oferta_url(@oferta), :class => "ver_mas")
    %br


.ofertas
  -@ofertas.each do |oferta|
    .oferta
      .social
        .fb-like{"data-href"=>cool_oferta_url(oferta), "data-send" => "false", "data-width" => "80", "data-layout" => "button_count", "data-show-faces" => "false"}
        %a.twitter-share-button{:href => "https://twitter.com/share", "data-url" => cool_oferta_url(oferta), "data-lang" => "en", "data-text" => oferta_full_description(oferta, true), "data-via" => "comidero"} tweet

      .imagen
        =image_tag(oferta.picture.url(:thumb))
      .info
        %h2=oferta.description.titleize
        en
        =oferta.restaurant.name.titleize
        %br
        %br
        -if !oferta.conditions.blank?
          %strong Condiciones
          %br
          =oferta.conditions
          %br
          %br
        -if !oferta.hour.blank?
          %strong Horario en el que aplica
          %br
          =oferta.hour
          %br
      =link_to("Ver más", cool_oferta_url(oferta), :class => "ver_mas")

app/views/layouts/application.html.haml
%html
  %head
    -if !yield(:title).blank?
      %title="Comidero :: " + yield(:title)
    -else
      %title Comidero

    -if !yield(:description).blank?
      %meta{:content => yield(:description), :name => "description"}
    -else
      %meta{:content => "Obten promociones en comida, hoy.", :name => "description"}

    %meta{:content => "descuentos, comida, guadalajara, hoy", :name => "keywords"}

    %link{:rel=>"icon", :type=>"image/png", :href=>"/images/comidero_small.png"}
    =yield(:meta)
    =stylesheet_link_tag 'reset'
    %link{:href => 'http://fonts.googleapis.com/css?family=Righteous', :rel => 'stylesheet', :type => 'text/css'}
    =stylesheet_link_tag 'application'
    =javascript_include_tag "https://maps.googleapis.com/maps/api/js?sensor=false"
    =javascript_include_tag :defaults, "nested_form"
    =csrf_meta_tag
    =yield(:javascript)
  %body
    #fb-root
    %script
      (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/es_LA/all.js#xfbml=1&appId=369418443117706";
      fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
      !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
    %script{:type=>"text/javascript"}
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-32423589-1']);
      _gaq.push(['_trackPageview']);
      (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();



    #header
      .header_info
        =link_to(image_tag('comidero.png', :width => "250px"),'/')
        =link_to('publica una promoción', new_restaurant_url, :class => 'publica_url')
    #content
      %ul#days
        -day_list.each_with_index do |day, index|
          -if params[:wday] and params[:wday] == day.parameterize
            %li=link_to(day, '/ofertas/' + day.parameterize, :class => "current_day")
          -elsif params[:wday].nil? and index == 0
            %li=link_to(day, '/ofertas/' + day.parameterize, :class => "current_day")
          -else
            %li=link_to(day, '/ofertas/' + day.parameterize)
      #main
        =yield

app/views/ofertas/new.html.haml
#new_oferta
  %h1 Publica una promoción
  =nested_form_for @oferta, :html => { :multipart => true } do |f|
    .field
      =f.label 'Id Restaurante'
      %br
      =f.text_field :restaurant_id

    =render 'restaurants/oferta_fields', :f => f

    =f.submit

app/views/ofertas/show.html.haml
-content_for :title do
  =oferta_full_description(@oferta)

-content_for :description do
  =oferta_full_description(@oferta)

-content_for :meta do
  %meta{:property=>"og:title", :content=>oferta_full_description(@oferta, true)}
  %meta{:property=>"og:type", :content=>"food"}
  %meta{:property=>"og:url", :content=>cool_oferta_url(@oferta)}
  %meta{:property=>"og:image", :content=>@oferta.picture.url(:medium)}
  %meta{:property=>"og:site_name", :content=>"Comidero"}
  %meta{:property=>"fb:app_id", :content=>"369418443117706"}
  %meta{:property=>"og:description", :content=>oferta_full_description(@oferta) + " Válida sólo los " + @oferta.valid_days.to_sentence.gsub(', and', ' y').gsub('and', 'y') + "."}

-content_for :javascript do
  %script{:type=>"text/javascript"}
    var sucursales = [
    -if @oferta.restaurant.addresses
      -@oferta.restaurant.addresses.each_with_index do |suc, index|
        -if !suc.latitude.blank? and !suc.longitude.blank?
          -if index < @oferta.restaurant.addresses.count - 1
            new google.maps.LatLng(#{suc.latitude}, #{suc.longitude}),
          -else
            new google.maps.LatLng(#{suc.latitude}, #{suc.longitude})
    ];

#oferta
  #main_oferta
    .social_main
      .fb-like{"data-href"=>cool_oferta_url(@oferta), "data-send" => "false", "data-width" => "80", "data-layout" => "button_count", "data-show-faces" => "false"}
      %a.twitter-share-button{:href => "https://twitter.com/share", "data-url" => cool_oferta_url(@oferta), "data-lang" => "en", "data-text" => oferta_full_description(@oferta, true), "data-via" => "comidero"} tweet

    .imagen
      .imagen2
        =image_tag(@oferta.picture.url(:medium))
    .info
      %h2
        =@oferta.description.titleize
        %br
      %span=' en ' + @oferta.restaurant.name.titleize
      %br
      %br
      -if !@oferta.hour.blank?
        %strong Horario en el que aplica
        %br
        =@oferta.hour
        %br
      %br
      -if !@oferta.conditions.blank?
        .conditions
          %strong Condiciones
          %br
          =@oferta.conditions
          %br
          %br

  -if @oferta.restaurant.addresses
    #sucursales
      %h3 Sucursales
      #mapa
        #map_canvas
      -@oferta.restaurant.addresses.each do |suc|
        .sucursal
          %strong Dirección:
          =suc.street
          %br
          =raw suc.street2 + "<br />" unless suc.street2.blank?
          -unless suc.phone.blank?
            %strong Tel:
            =suc.phone




  .fb-comments{"data-href"=>"http://comidero.com", "data-num-posts"=>"2", "data-width"=>"670"}

app/views/restaurants/_address_fields.html.haml
.local
  .field
    =f.label "Ciudad"
    =f.select :city, ['Guadalajara']
  .field
    =f.label 'Teléfono'
    =f.text_field :phone
  .field
    =f.label 'Dirección'
    %br
    =f.text_field :street
  .field
    =f.text_field :street2
  .field
    =f.link_to_remove "Quitar Local"

app/views/restaurants/_form.html.haml
.field
  =f.label 'Nombre del Restaurante'
  %br
  =f.text_field :name

.field
  =f.label 'Logotipo'
  %br
  =f.file_field :logo


=f.fields_for :ofertas


=f.fields_for :addresses
%br
.field{:style => 'text-align: right'}
  =f.link_to_add "Agregar otro local", :addresses
%br
=f.submit

app/views/restaurants/_oferta_fields.html.haml
.field
  =f.label 'Descripción de la Promoción'
  %br
  =f.text_field :description

.field
  =f.label '¿Cuándo expira?'
  %br
  =f.date_select :validity

.field
  =f.label '¿En cuáles días aplica la promoción?'
  %br
  .day_list
    =f.check_box :days, {:multiple => true}, 1
    =f.label 'Lunes', :for => "restaurant_ofertas_attributes_0_days_1"
    %br
    =f.check_box :days, {:multiple => true}, 2
    =f.label 'Martes', :for => "restaurant_ofertas_attributes_0_days_2"
    %br
    =f.check_box :days, {:multiple => true}, 3
    =f.label 'Miércoles', :for => "restaurant_ofertas_attributes_0_days_3"
    %br
    =f.check_box :days, {:multiple => true}, 4
    =f.label 'Jueves', :for => "restaurant_ofertas_attributes_0_days_4"
    %br
    =f.check_box :days, {:multiple => true}, 5
    =f.label 'Viernes', :for => "restaurant_ofertas_attributes_0_days_5"
    %br
    =f.check_box :days, {:multiple => true}, 6
    =f.label 'Sábado', :for => "restaurant_ofertas_attributes_0_days_6"
    %br
    =f.check_box :days, {:multiple => true}, 7
    =f.label 'Domingo', :for => "restaurant_ofertas_attributes_0_days_7"
    %br

.field
  =f.label '¿A que hora es valida?'
  %br
  =f.text_field :hour, :placeholder => "Ej: 3:00pm - 5:00 pm"

.field
  =f.label 'Condiciones'
  %br
  =f.text_area :conditions

.field
  =f.label 'Foto de la Comida'
  %br
  =f.file_field :picture

app/views/restaurants/new.html.haml
#new_oferta
  %h1 Publica una promoción
  =nested_form_for @restaurant, :html => { :multipart => true } do |f|
    =render 'form', :f => f